SystemOrganization addCategory: #Logikos!
SystemOrganization addCategory: #'Logikos-API'!
SystemOrganization addCategory: #'Logikos-ahp-model'!
SystemOrganization addCategory: #'Logikos-ahp-tests'!
SystemOrganization addCategory: #'Logikos-ahp-web'!
SystemOrganization addCategory: #'Logikos-common-web'!
SystemOrganization addCategory: #'Logikos-data-model'!
SystemOrganization addCategory: #'Logikos-data-web'!
